package botredirect

// getAdvancedBotUserAgents возвращает расширенный список User-Agent паттернов ботов
// Организован по категориям для лучшей производительности и понимания
func getAdvancedBotUserAgents() []string {
	return []string{
		// === ПОИСКОВЫЕ СИСТЕМЫ ===
		
		// Google
		"Googlebot",
		"Googlebot-Mobile",
		"Googlebot-Image",
		"Googlebot-News", 
		"Googlebot-Video",
		"Google-InspectionTool",
		"GoogleOther",
		"Google-Site-Verification",
		"Google-SearchByImage",
		"Feedfetcher-Google",
		"Google-Read-Aloud",
		"DuplexWeb-Google",
		"googleweblight",
		"Storebot-Google",
		"Google-PageRenderer",
		"Google-PhysicalWeb",
		"Google-Structured-Data-Testing-Tool",
		"APIs-Google",
		"AdsBot-Google",
		"AdsBot-Google-Mobile",
		"MediaPartners-Google",
		"Google-AMPHTML",
		
		// Microsoft Bing
		"bingbot",
		"BingPreview",
		"msnbot",
		"msnbot-media",
		"adidxbot",
		"BingLocalSearch",
		"BingBot",
		"MicrosoftPreview",
		"MSNBot-NewsBlogs",
		"MSNBot-Academic",
		
		// Yandex  
		"YandexBot",
		"YandexAccessibilityBot",
		"YandexMobileBot",
		"YandexDirectDyn",
		"YandexScreenshotBot",
		"YandexImages",
		"YandexVideo",
		"YandexVideoParser",
		"YandexMedia",
		"YandexBlogs",
		"YandexFavicons",
		"YandexWebmaster",
		"YandexPagechecker",
		"YandexImageResizer",
		"YandexAdNet",
		"YandexDirect",
		"YaDirectFetcher",
		"YandexCalendar",
		"YandexSitelinks",
		"YandexMetrika",
		"YandexNews",
		"YandexNewslinks",
		"YandexCatalog",
		"YandexAntivirus",
		"YandexMarket",
		"YandexVertis",
		"YandexForDomain",
		"YandexSpravBot",
		"YandexSearchShop",
		"YandexMedianaBot",
		"YandexOntoDB",
		"YandexOntoDBAPI",
		"YandexTurbo",
		"YandexVerticals",
		
		// Other Major Search Engines
		"DuckDuckBot",
		"DuckDuckGo-Favicons-Bot",
		"Baiduspider",
		"Baiduspider-render",
		"Baiduspider-image",
		"Baiduspider-video",
		"Baiduspider-news",
		"Sogou Spider",
		"Sogou web spider",
		"Sogou inst spider",
		"Sogou spider2",
		"Sogou blog",
		"Sogou News Spider",
		"Sogou Orion spider",
		"360Spider",
		"360User-agent",
		"HaosouSpider",
		"Slurp",
		"Yahoo! Slurp",
		"ia_archiver",
		"Teoma",
		"Jeeves",
		"AltaVista",
		"Lycos",
		"Scooter",
		"AltaVista-Intranet",
		"FAST-WebCrawler",
		"Ask Jeeves",
		"Speedy Spider",
		"Gigabot",
		"NaverBot",
		"Yeti",
		"SeznamBot",
		"Seznam screenshot-generator",
		"oBot",
		"Rambler",
		
		// === СОЦИАЛЬНЫЕ СЕТИ ===
		
		// Facebook
		"facebookexternalhit",
		"Facebot",
		"FacebookBot",
		"facebook-scraper",
		"WhatsApp",
		"facebookplatform",
		"facebookcatalog",
		
		// Twitter/X
		"Twitterbot",
		"TwitterBot",
		"X-Bot",
		
		// LinkedIn
		"LinkedInBot",
		"linkedin",
		
		// Other Social
		"TelegramBot",
		"SkypeUriPreview",
		"Skype-Url-Preview",
		"vkShare",
		"VK Share Button",
		"redditbot",
		"Slackbot",
		"Slackbot-LinkExpanding",
		"Discord",
		"DiscordBot",
		"TikTokBot",
		"PinterestBot",
		"Pinterest",
		"Applebot",
		"Snapchat",
		"InstagramBot",
		"YelpBot",
		"tumblr",
		"FlipboardProxy",
		"bitlybot",
		"ViKinkBot",
		"Line",
		"Viber",
		"KakaoTalk",
		"WeChat",
		
		// === SEO И АНАЛИЗ ===
		
		// Major SEO Tools
		"AhrefsBot",
		"ahrefs",
		"SemrushBot",
		"semrush",
		"MJ12bot",
		"DotBot",
		"MegaIndex",
		"MegaIndex.ru",
		"BLEXBot",
		"spbot",
		"linkdexbot",
		"LinkpadBot",
		"SiteAuditBot",
		"Lipperhey",
		"serpstatbot",
		"Moz",
		"rogerbot",
		"exabot",
		"SurdotlyBot",
		"Cliqzbot",
		"searchmetricsbot",
		"fr-crawler",
		"sistrix",
		"SISTRIX Crawler",
		"Optimizer",
		"SEOkicks",
		"seokicks-robot",
		"VoilaBot",
		"CrawlomaticBot",
		"BrandVerity",
		"check_mk",
		"SeoAuditBot",
		"SEOdiver",
		"SEOlyticsCrawler",
		"seoscanners",
		"VelenPublicWebCrawler",
		"epicbot",
		"trendictionbot",
		"Feedspotbot",
		"Seobility",
		"IstellaBot",
		"proximic",
		"changedetection",
		"Genieo",
		"WeSEE",
		"CCBot",
		"OpenHoseBot",
		"Qwantify",
		"MindUpBot",
		"RankActiveLinkBot",
		"Siteimprove",
		"BrightEdgeBot",
		
		// === МОНИТОРИНГ И АПТАЙМ ===
		
		// Uptime Monitoring
		"Pingdom",
		"pingdom",
		"UptimeRobot",
		"StatusCake",
		"Site24x7",
		"NodePing",
		"MonitorLobster",
		"WebSitePulse",
		"AlertSite",
		"AppDynamics",
		"Catchpoint",
		"ThousandEyes",
		"GTmetrix",
		"PageSpeed",
		"YottaaMonitor",
		"Rigor",
		"Monitis",
		"AlertBot",
		"WebPageTest",
		"Dotcom-Monitor",
		"SolarWinds",
		"Nagios",
		"Zabbix",
		"NewRelic",
		"DataDog",
		"PulsePointBot",
		
		// === БЕЗОПАСНОСТЬ ===
		
		// Security Scanners
		"Qualys",
		"Nessus",
		"OpenVAS",
		"Rapid7",
		"Acunetix",
		"NetSparker",
		"AppSpider",
		"WebInspect",
		"Burp",
		"w3af",
		"sqlmap",
		"Nikto",
		"dirb",
		"dirbuster",
		"gobuster",
		"wfuzz",
		"ZAP",
		"OWASP",
		"VulnBot",
		"SecurityBot",
		"ScanAlert",
		"Alert Logic",
		"Sucuri",
		"SiteLock",
		"Detectify",
		"HackerOne",
		"Bugcrowd",
		"PunkSPIDER",
		"CensysInspect",
		"ShodanBot",
		"masscan",
		"nmap",
		"zmap",
		
		// === АРХИВЫ И ИНДЕКСАТОРЫ ===
		
		// Web Archives
		"ia_archiver",
		"wayback",
		"WaybackMachine",
		"archive.org_bot",
		"ArchiveTeam",
		"WebCite",
		"webcitation",
		"CachedPage",
		"PageFreezer",
		"Preserve",
		"CommonCrawl",
		"CCBot",
		"commoncrawl",
		"GrapeshotCrawler",
		"DeuSu",
		"Wayback Machine",
		
		// Academic/Research
		"CiteSeerX",
		"ResearchBot",
		"AcademicBot",
		"ScholarBot",
		"ScienceBot",
		"PubMedBot",
		"ArXivBot",
		"SemanticBot",
		"DBLPBot",
		"GSABot",
		"Microsoft Academic",
		"SemanticScholar",
		"CORE-bot",
		
		// === КОММЕРЧЕСКИЕ СЕРВИСЫ ===
		
		// E-commerce & Shopping
		"Shopify",
		"ShopifyBot",
		"Amazon",
		"AmazonBot",
		"Googlebot-Shopping",
		"BingBot-Shopping",
		"PriceGrabber",
		"Shopping.com",
		"Nextag",
		"Shopzilla",
		"NexTag",
		"Become",
		"Shopbot",
		"Froogle",
		"ProductBot",
		"CatalogBot",
		"DealBot",
		"OfferBot",
		"CompareBot",
		"ReviewBot",
		
		// News & Media
		"NewsBot",
		"NewsNow",
		"Moreover",
		"Topix",
		"NewsGator",
		"Feedzilla",
		"RSSBot",
		"FeedBot",
		"AtomBot",
		"SyndBot",
		"PodcastBot",
		"RadioBot",
		"TVBot",
		"MediaBot",
		"ContentBot",
		"ArticleBot",
		"BlogBot",
		"PostBot",
		
		// === GENERIC PATTERNS ===
		
		// Generic Bot Patterns
		"*bot*",
		"*crawler*", 
		"*spider*",
		"*scraper*",
		"*fetcher*",
		"*grabber*",
		"*extractor*",
		"*monitor*",
		"*checker*",
		"*validator*",
		"*scanner*",
		"*analyzer*",
		"*indexer*",
		"*reader*",
		"*parser*",
		"*archiver*",
		"*harvester*",
		"*collector*",
		"*gatherer*",
		"*probe*",
		"*test*",
		"*audit*",
		"*inspect*",
		"*survey*",
		"*review*",
		"*discover*",
		"*explore*",
		"*search*",
		"*find*",
		"*seek*",
		"*hunt*",
		"*track*",
		"*follow*",
		"*watch*",
		"*observe*",
		"*guard*",
		"*sentinel*",
		"*agent*",
		"*tool*",
		"*utility*",
		"*service*",
		"*daemon*",
		"*worker*",
		"*process*",
		"*script*",
		"*program*",
		"*application*",
		"*system*",
		"*engine*",
		"*library*",
		"*framework*",
		"*plugin*",
		"*module*",
		"*component*",
		"*widget*",
		"*gadget*",
		"*device*",
		"*client*",
		"*browser*",
		"*viewer*",
		"*player*",
		"*editor*",
		"*manager*",
		"*controller*",
		"*handler*",
		"*processor*",
		"*generator*",
		"*builder*",
		"*creator*",
		"*maker*",
		"*producer*",
		"*publisher*",
		"*distributor*",
		"*provider*",
		"*supplier*",
		"*vendor*",
		"*partner*",
		"*affiliate*",
		"*associate*",
		"*member*",
		"*user*",
		"*visitor*",
		"*guest*",
		"*anonymous*",
		"*unknown*",
		"*other*",
		
		// === СПЕЦИФИЧЕСКИЕ ПАТТЕРНЫ ===
		
		// Common Bot Suffixes/Prefixes
		".*bot$",
		"^bot.*",
		".*crawler$",
		"^crawler.*", 
		".*spider$",
		"^spider.*",
		".*fetch.*",
		".*scrape.*",
		".*index.*",
		".*crawl.*",
		".*scan.*",
		".*monitor.*",
		".*check.*",
		".*test.*",
		".*audit.*",
		".*probe.*",
		".*search.*",
		".*find.*",
		".*track.*",
		".*watch.*",
		".*agent.*",
		".*tool.*",
		".*util.*",
		".*auto.*",
		".*robot.*",
		".*machine.*",
		".*artificial.*",
		".*synthetic.*",
		".*automated.*",
		".*programmatic.*",
		
		// Version Patterns
		"bot/\\d+",
		"crawler/\\d+", 
		"spider/\\d+",
		".*bot.*\\d+",
		".*crawler.*\\d+",
		".*spider.*\\d+",
		
		// HTTP Library Patterns
		"curl",
		"wget",
		"HTTPie",
		"http_request2",
		"Python-urllib",
		"Python-requests",
		"python-requests",
		"Java",
		"okhttp",
		"Apache-HttpClient",
		"Guzzle",
		"libwww-perl",
		"WWW-Mechanize",
		"LWP::Simple",
		"NET::HTTP",
		"Go-http-client",
		"node-fetch",
		"axios",
		"got",
		"superagent",
		"request",
		"urllib",
		"httplib",
		"aiohttp",
		"tornado",
		"twisted",
		"scrapy",
		"mechanize",
		"selenium",
		"phantomjs",
		"headless",
		"zombie",
		"jsdom",
		
		// Headless Browsers
		"HeadlessChrome",
		"PhantomJS",
		"SlimerJS",
		"HtmlUnit",
		"Splash",
		"Puppeteer",
		"Playwright",
		"ChromeHeadless",
		"FirefoxHeadless",
		"SafariHeadless",
		"EdgeHeadless",
		
		// === ПОДОЗРИТЕЛЬНЫЕ ПАТТЕРНЫ ===
		
		// Suspicious/Malicious
		"masscan",
		"nmap",
		"zmap",
		"zgrab",
		"Banner Grab",
		"Banner Grabber",
		"Port Scanner",
		"Security Scanner",
		"Vulnerability Scanner",
		"SQL Injection",
		"XSS Scanner",
		"Web Application Scanner",
		"Directory Scanner",
		"File Scanner",
		"Admin Scanner",
		"Login Scanner",
		"Password Scanner",
		"Brute Force",
		"Dictionary Attack",
		"Credential Stuffing",
		"Account Takeover",
		"Click Fraud",
		"Ad Fraud",
		"Bot Traffic",
		"Fake Traffic",
		"Synthetic Traffic",
		"Automated Traffic",
		"Non-Human Traffic",
		"Malicious Bot",
		"Bad Bot",
		"Hostile Bot",
		"Aggressive Bot",
		"Unauthorized Bot",
		"Rogue Bot",
		"Spam Bot",
		"Scraping Bot",
		"Harvesting Bot",
		"Data Mining Bot",
		"Content Theft Bot",
		"Copyright Violation Bot",
		"License Violation Bot",
		"Terms Violation Bot",
		"Policy Violation Bot",
		"Abuse Bot",
		"Attack Bot",
		"Exploit Bot",
		"Penetration Test",
		"Security Test",
		"Pen Test",
		"Red Team",
		"Blue Team",
		"White Hat",
		"Black Hat",
		"Grey Hat",
		"Ethical Hacker",
		"Bug Bounty",
		"Responsible Disclosure",
		"Security Research",
		"Academic Research",
		"Commercial Research",
		"Market Research",
		"Competitor Analysis",
		"Price Monitoring",
		"Availability Monitoring",
		"Content Monitoring",
		"Change Detection",
		"Update Notification",
		"Alert System",
		"Warning System",
		"Notification System",
		"Monitoring System",
		"Tracking System",
		"Analytics System",
		"Measurement System",
		"Reporting System",
		"Dashboard System",
		"Control Panel",
		"Admin Panel",
		"Management Console",
		"Configuration Tool",
		"Setup Wizard",
		"Installation Script",
		"Deployment Tool",
	}
}

// getBasicBotUserAgents возвращает базовый список User-Agent паттернов
func getBasicBotUserAgents() []string {
	return []string{
		// Основные поисковые системы
		"Googlebot",
		"bingbot",
		"YandexBot",
		"DuckDuckBot",
		"Baiduspider",
		"Sogou",
		"360Spider",
		
		// Социальные сети
		"facebookexternalhit",
		"Twitterbot",
		"LinkedInBot",
		"WhatsApp",
		"TelegramBot",
		"Applebot",
		
		// SEO инструменты
		"AhrefsBot",
		"SemrushBot",
		"MJ12bot",
		"rogerbot",
		"DotBot",
		
		// Мониторинг
		"Pingdom",
		"UptimeRobot",
		"StatusCake",
		
		// Общие паттерны
		"*bot*",
		"*crawler*",
		"*spider*",
		"crawler",
		"spider",
		"bot",
		"crawl",
		"slurp",
		"scraper",
		"fetch",
		"monitor",
		"archive",
		"check",
		"test",
		"validator",
		"indexer",
		"reader",
		"parser",
		"extractor",
		"getter",
		"scanner",
		"analyzer",
		"collector",
		"gatherer",
		"harvester",
		"probe",
		"audit",
		"inspect",
		"survey",
		"review",
		"discover",
		"explore",
		"search",
		"find",
		"seek",
		"hunt",
		"track",
		"follow",
		"watch",
		"observe",
		"monitor",
		"guard",
		"sentinel",
		"agent",
		"tool",
		"utility",
		"service",
		"daemon",
		"worker",
		"process",
		"script",
		"program",
		"application",
		"system",
		"engine",
		"library",
		"framework",
		"plugin",
		"module",
		"component",
		"widget",
		"gadget",
		"device",
		"client",
		"browser",
		"viewer",
		"player",
		"editor",
		"manager",
		"controller",
		"handler",
		"processor",
		"generator",
		"builder",
		"creator",
		"maker",
		"producer",
		"publisher",
		"distributor",
		"provider",
		"supplier",
		"vendor",
		"partner",
		"affiliate",
		"associate",
		"member",
		"user",
		"visitor",
		"guest",
		"anonymous",
		"unknown",
		"other",
	}
}

// getBotUserAgentsByCategory возвращает паттерны по категориям
func getBotUserAgentsByCategory() map[string][]string {
	return map[string][]string{
		"search_engines": {
			"Googlebot", "Google-InspectionTool", "GoogleOther",
			"bingbot", "BingPreview", "msnbot",
			"YandexBot", "YandexImages", "YandexVideo",
			"DuckDuckBot", "Baiduspider", "Sogou", "360Spider",
		},
		"social_media": {
			"facebookexternalhit", "Facebot", "FacebookBot",
			"Twitterbot", "TwitterBot", "LinkedInBot",
			"WhatsApp", "TelegramBot", "SkypeUriPreview",
			"vkShare", "redditbot", "Slackbot", "Discord",
			"TikTokBot", "PinterestBot", "Applebot",
		},
		"seo_tools": {
			"AhrefsBot", "SemrushBot", "MJ12bot", "DotBot",
			"BLEXBot", "rogerbot", "exabot", "sistrix",
			"SEOkicks", "Seobility", "proximic",
		},
		"monitoring": {
			"Pingdom", "UptimeRobot", "StatusCake", "Site24x7",
			"NodePing", "AlertSite", "GTmetrix", "PageSpeed",
			"WebPageTest", "Dotcom-Monitor",
		},
		"security": {
			"Qualys", "Nessus", "OpenVAS", "Acunetix",
			"Burp", "ZAP", "ShodanBot", "masscan", "nmap",
		},
		"archives": {
			"ia_archiver", "wayback", "ArchiveTeam", "WebCite",
			"CommonCrawl", "CCBot", "GrapeshotCrawler",
		},
		"http_libraries": {
			"curl", "wget", "HTTPie", "Python-urllib",
			"Python-requests", "Go-http-client", "node-fetch",
			"axios", "scrapy", "mechanize",
		},
		"headless_browsers": {
			"HeadlessChrome", "PhantomJS", "Puppeteer",
			"Playwright", "ChromeHeadless", "headless",
		},
	}
}

// getHighConfidenceBotPatterns возвращает паттерны с высокой степенью уверенности
func getHighConfidenceBotPatterns() []string {
	return []string{
		// Только проверенные боты поисковых систем
		"Googlebot",
		"Google-InspectionTool",
		"bingbot",
		"BingPreview", 
		"YandexBot",
		"YandexImages",
		"DuckDuckBot",
		"Baiduspider",
		"facebookexternalhit",
		"Twitterbot",
		"LinkedInBot",
		"AhrefsBot",
		"SemrushBot",
		"Pingdom",
		"UptimeRobot",
	}
}

// getSuspiciousBotPatterns возвращает подозрительные паттерны
func getSuspiciousBotPatterns() []string {
	return []string{
		"masscan",
		"nmap",
		"zmap",
		"sqlmap",
		"Nikto",
		"dirb",
		"gobuster",
		"wfuzz",
		"Burp",
		"Security Scanner",
		"Vulnerability Scanner",
		"Penetration Test",
		"Brute Force",
		"Bot Traffic",
		"Malicious Bot",
		"Scraping Bot",
		"Data Mining Bot",
		"Content Theft Bot",
	}
}